apiVersion: v1
kind: Service
metadata:
  name: k8s-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing

spec:
  selector:
    app: my-app
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP
  type: LoadBalancer